#!/bin/sh

ssh andijani@178.128.53.245 <<EOF
 cd ~/node-app-ci-cd
 echo $PATH
 git pull
 npm --version
 npm install --production
 /home/andijani/.nvm/versions/node/v17.9.0/bin/pm2 --version
 /home/andijani/.nvm/versions/node/v17.9.0/bin/pm2 restart all
 exit
EOF